spring:
  application:
    name: example

  redis:
    host: 127.0.0.1
    port: 6379
    #连接超时时间
    timeout: 10s
    lettuce:
      pool:
        #最大连接数
        max-active: 35
        #最大阻塞等待时间(负数表示没限制)
        max-wait: 5s
        #最大空闲
        max-idle: 16
        #最小空闲
        min-idle: 0
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    schema: classpath:db/schema.sql

#    data: classpath:db/data.sql
    url: jdbc:mysql://127.0.0.1:3306/service_test?useUnicode=true&characterEncoding=utf8&useSSL=false&useSSL=true&serverTimezone=GMT%2b8
    username: root
    password: root
    initialization-mode: always

# MP 配置
mybatis-plus:
#  type-enums-package: com.yangbingdong.service.mp.enums
  global-config:
    db-config:
      id-type: input
  configuration:
    cache-enabled: true


alchemist:
  mvc:
    oplog: true
    disruptor:
      power: 11
      worker: 2
  redisoper:
    serialize-type: protostuff
    orm-type: mp
    dlock:
      enable: false
      dLockType: redisson
  auth:
    enable-jwt-session: true
    local-session-cache-maximum-size: 50000
    local-session-expire-second: 300
